vich_uploader:
    db_driver: orm
    storage: '@app.vich_storage.s3'
    metadata: 
        type: attribute

    mappings:
        phenotype_docs:
            uri_prefix: /docs/phenotype
            upload_destination: '%kernel.project_dir%/public/docs/phenotype'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        sequencing_docs:
            uri_prefix: /docs/sequencing
            upload_destination: '%kernel.project_dir%/public/docs/sequencing'
            namer: 'App\Service\PreserveExtensionNamer'


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        drug_docs: 
            uri_prefix: /docs/drugs
            upload_destination: '%kernel.project_dir%/public/docs/drugs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
